### ISSUE TITLE
Create django app - query 

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#10]
**Is your feature request related to a problem? Please describe.**
We need a django app to create python logic for query and query related operations.

**Describe the solution you'd like**
1. create django app **query**.
2. add the app to settings.py
3. create urls.py under users app
4. include **query/urls.py** in the **server/urls.py** with prefix **api/query/**

**Comment by sahil9001** [comment]
https://github.com/ECellNitrr/teesco-backend/pull/13
