### ISSUE TITLE
Create Permission set api

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#100]
**Is your feature request related to a problem? Please describe.**
As an admin of the organisation I would like to view the list of groups available in the org.

![image](https://user-images.githubusercontent.com/33046846/82784831-f7484d00-9e7e-11ea-99b3-2e7a53dd7a69.png)

**Describe the solution you'd like**
1. Create an api: `[post] /api/org/(org-id)/permission_set/` which creates a permission set.
1. only **admin** of that org can access this api.
1. make swagger docs for the same 
1. add tests for the same
1. It will takes in 
```
{
  "name" : "some name",
  "permissions": [1,3,0] # an array of permission ints 
}
```

**Comment by priyanshisharma** [comment]
Since we've gotten rid of the Permission Set model (with reference to #105 and #106 ), I suppose this issue shall be closed now.
