### ISSUE TITLE
Mock Email Service and AWS SES support

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#108]
**Is your feature request related to a problem? Please describe.**
A developer I should be able to mock emails when developing API's which involve them. :sunglasses: 

**Describe the solution you'd like**
1. Create envvar `MOCK_EMAIL`(bool)  and  `EMAIL_BACKEND`(string)
1. If set to `True` should print the email detail in the console instead of sending the actual email.
1. If set to `False` should require the user to specify `EMAIL_BACKEND` which can either  be `DJANGO-SMTP` or  `AWS-SES`. For other value it should raise UNEXPECTED_EMAIL_BACKEND exception.
1. if `DJANGO-SMTP` is set then it should take in  `EMAIL_HOST_USER` and  `EMAIL_HOST_PASSWORD` envvars. If missing it should raise `INVALID_DJANGO_SMTP_CREDENTIALS` exception.
1. if `AWS-SES` is set then it should take in `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` envvars. If missing it should raise `INVALID_AWS_SES_CREDENTIALS` exception.
1. update requirements.txt
1. Update readme.md
1. DM me on slack for obtaining AWS credentials for testing purposes. :v: 

**Describe alternatives you've considered**

**References**
https://github.com/anitab-org/mentorship-backend/pull/525. Something like this is expected.

**Comment by sahil9001** [comment]
Can I take this issue?
