### ISSUE TITLE
Create django app - org

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#11]
**Is your feature request related to a problem? Please describe.**
We need a django app to create python logic for org and org related operations.

**Describe the solution you'd like**
1. create django app **org**.
2. add the app to settings.py
3. create urls.py under org app
4. include **org/urls.py** in the **server/urls.py** with prefix **api/org/**

**Comment by priyanshisharma** [comment]
#21

**Comment by priyanshisharma** [comment]
#22

**Comment by PratibhaShrivastav** [comment]
Merged #11
