### ISSUE TITLE
Create django app - tasks

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#12]
**Is your feature request related to a problem? Please describe.**
We need a django app to create python logic for tasks and tasks related operations.

**Describe the solution you'd like**
1. create django app **tasks**.
2. add the app to settings.py
3. create urls.py under tasks app
4. include **tasks/urls.py** in the **server/urls.py** with prefix **api/tasks/**

**Comment by priyanshisharma** [comment]
#21

**Comment by priyanshisharma** [comment]
#23

**Comment by PratibhaShrivastav** [comment]
Merged #12
