### ISSUE TITLE
org info API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#120]
**Is your feature request related to a problem? Please describe.**
As a user, I should be able to see the info of an org.

**Describe the solution you'd like**
1. Create an api: `[get] /api/org/(org-id)/` which return org info.
1. only authenticated users can access this API.
1. make swagger docs for the same 
1. add tests for the same

**response**
```
{
    "id" : <id>  
    "route_slug" : <route_slug>  
    "can_join_without_invite" : <can_join_without_invite>    
    "name" : <name>  
    "tagline" : <tagline>  
    "about" : <about>   
    "profile_pic" : <profile_pic>   
    "cover_pic" : <cover_pic>  
}
```

**Comment by sahil9001** [comment]
I am taking this issue.
