### ISSUE TITLE
create task API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#121]
**Is your feature request related to a problem? Please describe.**
As a staff of the org I should be able to create tasks for the volunteers.

![image](https://user-images.githubusercontent.com/33046846/83736198-e8c41780-a66e-11ea-9dc6-e3923778b9e8.png)

**Describe the solution you'd like**
1. Create an api: `[post] /api/tasks/org/(org-id)/` which creates a task.
1. only **staff** of that org with **CAN_CREATE_TASKS** permission can create a task.
1. make swagger docs for the same 
1. add tests for the same
1. limit choices to social_media_platform field in task model as (don't forget to create migrations)
    1. facebook
    1. whatsapp
    1. linkedin
    1. youtube
    1. instagram
    1. twitter
    1. other
    1. (we are trying to be professional here so TIKTOK is out of the question)\
1. the API should take
    1. org_id
    1. social_media_platform
    1. description 
    1. only one out of (share_link,share_text,share_img) 
1. should return appropriate errors are the edge cases
1. transfer data using `formdata` as it contains picture.

The API has quite some stuff going on so if you have doubts don't hesitate to ask in the slack :innocent:

**Comment by priyanshisharma** [comment]
I'm working on this issue.
