### ISSUE TITLE
invite link detail api

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#135]
**Is your feature request related to a problem? Please describe.**
As a **about to be a new user** to an organization when I visit the invite link sent by the org is should be able to see the details of the invite.

![image](https://user-images.githubusercontent.com/33046846/84573868-bfb72b80-adc0-11ea-99b6-95ce0c59b1da.png)

**Describe the solution you'd like**
create an API `/org/invite/{invite_slug}/` which will provide the following details to the user
1. org name
1. org tagline
1. org profile img
1. group name

User need not be authenticated to use this API.

**Comment by priyanshisharma** [comment]
I'm working on this issue.
