### ISSUE TITLE
Create models of users app

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#19]
### has to done once #9 is solved

**Is your feature request related to a problem? Please describe.**
Create models of users app.

**Describe the solution you'd like**
1. Create User and Notification model under users app as described in https://dbdiagram.io/d/5e97237739d18f5553fda63b . 
1. After creating the two models create a migration file for the same.

**Comment by priyanshisharma** [comment]
#21

**Comment by priyanshisharma** [comment]
#24

**Comment by priyanshisharma** [comment]
Please refer to #28
