### ISSUE TITLE
Add urlpatterns in 'users' and 'query' app

### ISSUE THREAD

**Issue by sahil9001** [ECellNitrr/teesco-backend#26]
**Is your feature request related to a problem? Please describe.**
I forgot to add urlpatterns in 'users' and 'query' which were causing setup issues.

**Describe the solution you'd like**
Modified 'users/urls.py' and 'query/urls.py' to add 'urlpatterns'

**Describe alternatives you've considered**

**Additional context**

**Comment by naveennvrgup** [comment]
In the issue template, please delete the sections/questions you have no answered.
