### ISSUE TITLE
Create models of org app

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#30]
**Is your feature request related to a problem? Please describe.**
This issue should be attempted only after #29. Create models of org app. The db design is provided here https://dbdiagram.io/d/5e97237739d18f5553fda63b.

**Describe the solution you'd like**
Create these models in the org app:
1. Org
1. Group
1. Member
1. PermissionSet
1. Leaderboard

Generate a migrations file after creating the model.

Make use of PermissionsSetField Created in the #29 in PermissionSet model.

**Comment by priyanshisharma** [comment]
I would like to work on this issue.
