### ISSUE TITLE
Setup Email service utils

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#52]
**Is your feature request related to a problem? Please describe.**
For notification purposes we require to send emails. So we a email service setup.

**Describe the solution you'd like**
1. Create a folder utils under project root
1. create utils.email_service.send_email(recipient: str, subject: str: body: str) 
1. create the necessary setup that when this function is called the email is sent.
1. Update readme file.

**Comment by anshsrtv** [comment]
I am working on this
