### ISSUE TITLE
Volunteering API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#64]
**Is your feature request related to a problem? Please describe.**
As user I should be able to volunteer to organisations

**Describe the solution you'd like**
1. Create api [get] /api/org/(org-id)/volunteer/ which adds the user sending the volunteer request into group "volunteer" of the organisation.
1. Make sure the user is not already a part of the org.
1. Add appropriate tests.
1. Add swagger docs for the same.

**Comment by sahil9001** [comment]
Can I take up this issue?
@naveennvrgup sir

**Comment by naveennvrgup** [comment]
> Can I take up this issue?
> @naveennvrgup sir

sure this issue is assigned to you

**Comment by naveennvrgup** [comment]
You can create org and volunteer group with the help of django admin or `./manage.py shell`. (until atleast #63 is solved.) :smile:

**Comment by sahil9001** [comment]
So shall I wait until #63 is solved then work on this?

**Comment by naveennvrgup** [comment]
No need to wait just just to the prep b4 working:
1. create one or two orgs. 
1. create a volunteer permission set (zero permissions) for every org
1. create a volunteer group for each org
1. when volunteer hits the api they are now put into the volunteer group.

**Comment by naveennvrgup** [comment]
> So shall I wait until #63 is solved then work on this?

Now #63 is solved @sahil9001 :innocent:

**Comment by sahil9001** [comment]
Yes sir I'll do this now.
