### ISSUE TITLE
Edit org profile API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#65]
**Is your feature request related to a problem? Please describe.**
As a admin of the org I should be able to edit org profile.

**Describe the solution you'd like**
1. Create api [put] /api/org/(org-id)/ which takes in the below and updates the existing with the new value :
    1. org name
    1. tagline
    1. about
1. only admins should be able to edit this.
1. Add appropriate tests.
1. Add swagger docs for the same.

**Comment by sahil9001** [comment]
I have my exams on 24th, can I do this after that?
