### ISSUE TITLE
update profile_pic api

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#66]
**Is your feature request related to a problem? Please describe.**
As a admin of the org I should be able to update the profile_pic/logo of the org.

**Describe the solution you'd like**
1. Create api [put] /api/org/(org-id)/profile_pic/ which takes in new pic which replaces the old one.
1. Make sure to delete the old pic.
1. Only admin should able to perform this task.
1. Add appropriate tests.
1. Add swagger docs for the same.

**Comment by anshsrtv** [comment]
Can I take up this issue since @akhil-maker is facing problems solving this?
