### ISSUE TITLE
Create group API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#68]
**Is your feature request related to a problem? Please describe.**
As a admin of the org I should be able create new group of members.

![image](https://user-images.githubusercontent.com/33046846/81894020-7d85a900-95cc-11ea-9bd7-85228ffe40e0.png)

**Describe the solution you'd like**
1. Create `api [post] /api/org/(org-id)/group/` which takes in the below and creates a new group under the given org :
    1. group name
    1. group role
    1. permission set id
1. only admins should be able use this api.
1. Add appropriate tests.
1. Add swagger docs for the same.

**Comment by anshsrtv** [comment]
I am working on this✌️

**Comment by naveennvrgup** [comment]
i am assigning this issue to @anshsrtv

**Comment by anshsrtv** [comment]
What will perm_obj take as a value now?
An array i suppose?

**Comment by naveennvrgup** [comment]
@anshsrtv  with pr #106 the scenario is changed now: instead  of `permission_set` id it will `permissions` (array of permission ints) and the updated screenshot is:

![image](https://user-images.githubusercontent.com/33046846/83324631-4c6fce80-a284-11ea-8e00-cde49b81fd2e.png)

**Comment by naveennvrgup** [comment]
make sure to validate that each permission int is a valid one

**Comment by anshsrtv** [comment]
We just have 5 permissions, right??
