### ISSUE TITLE
permission_set list api

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#69]
**Is your feature request related to a problem? Please describe.**
As a admin of the organisation i would like to view the list of permission sets available in the org.

![image](https://user-images.githubusercontent.com/33046846/81894428-60050f00-95cd-11ea-8e6b-b63ff0352dfb.png)

**Describe the solution you'd like**
1. Create an api: `[get] /api/org/(org-id)/permission_set/` which lists the permissions sets available under that org.
1. It will return an array of permission_set objects which contain 
    1. permission_set.id 
    1. permission_set.name
(no need of role and actual permission info here as we can see from img)
1. only **authenticated users** can access it.
1. only **staff** of that org can access this api.
1. make swagger docs for the same 
1. add tests for the same

**Comment by sahil9001** [comment]
Can I take up this issue?
