### ISSUE TITLE
Add swagger docs support

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#8]
**Is your feature request related to a problem? Please describe.**
It is great to have all API docs in one place. Especially if it is interactive and provides examples on response, request body etc., 

**Describe the solution you'd like**
Integrate swagger docs into the django server with help of django-yasg package.

**Comment by naveennvrgup** [comment]
I would like to work on this issue.

**Comment by sumit-badsara** [comment]
@KunalAnkur create a fresh new PR, from a new branch.

**Comment by naveennvrgup** [comment]
@sahil9001 Please take over this issue from @KunalAnkur
