### ISSUE TITLE
Error messages for unregistered users in login api

### ISSUE THREAD

**Issue by pratik0204** [ECellNitrr/teesco-backend#87]
**Is your feature request related to a problem? Please describe.**
Bug report regarding issue #51 , no error messages for users who are not registered.

**Describe the solution you'd like**
The errors in the api response should be -

**response:** 
```
{
  "email": [
    "This field is required."
    "Email is incorrect or not registered"
  ],
  "password": [
    "This field is required."
  ]
}
```

**The errors can be generated as-**
1."Field is required" for empty fields.
2."Email is incorrect or not registered" for valid but incorrect email posted.
3."Credentials did not match" for incorrect password.

**Additional context**
Suggestions or better modifications are appreciated.
[Queries are appreciated in the form of comments to this issue]

**Comment by naveennvrgup** [comment]
1. Currently the login API says `incorrect credentials` when the email and passwords doesn't match.
2. A solution to @pratik0204's suggestion can be, we can check if that user is present in our system or not, before we try to check their credentials.

**Comment by naveennvrgup** [comment]
I am assigning this issue to @kunalAnkur

**Comment by KunalAnkur** [comment]
@naveennvrgup  okay sir
