### ISSUE TITLE
Create django app - users

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#9]
**Is your feature request related to a problem? Please describe.**
We need a django app to create python logic for users and user related operations.

**Describe the solution you'd like**
1. create django app **users**.
2. add the app to settings.py
3. create urls.py under users app
4. include **users/urls.py** in the **server/urls.py** with prefix **api/users/**

**Comment by sahil9001** [comment]
https://github.com/ECellNitrr/teesco-backend/pull/13
