### ISSUE TITLE
Group list API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-backend#98]
**Is your feature request related to a problem? Please describe.**
As a admin of the organisation i would like to view the list of groups available in the org.

![image](https://user-images.githubusercontent.com/33046846/82784104-7b99d080-9e7d-11ea-96a2-bcbfa237c264.png)

**Describe the solution you'd like**
1. Create an api: `[get] /api/org/(org-id)/group/` which lists the groups available under that org.
1. It will return an array of groups objects which contain 
    1. group.id 
    1. group.name
    1. Number of members in that group (member_count)
(no need of role and actual permission info here as we can see from img)
1. only **staff** of that org can access this api.
1. make swagger docs for the same 
1. add tests for the same

**Comment by KunalAnkur** [comment]
@naveennvrgup  okay sir I am working on it.
